### ISSUE TITLE
Locker issuse in security

### ISSUE THREAD

**Issue by alexkar598** [miniusAreas/mA-Mapping-Division-Sunset#12]
![image](https://user-images.githubusercontent.com/25136265/46575275-8dfd8880-c980-11e8-8274-42cd3aa756df.png)
it dosent go in the locker

undocumented changes:
addition of sec hud in clothing locker
addition of armour in clothing locker
addition of shoulder holsters in clothing locker
addition of helmets in the clothing locker

**Comment by miniusAreas** [comment]
Roger, moving the huds to another location, and removing the beanies.
